### ISSUE TITLE
Error in Log

### ISSUE THREAD

**Issue by RtBower** [fdbozzo/foxbin2prg#8] opened 2017-11-27 11:50 UTC
I'm not sure if this is pointing to a larger problem or not, but the individual file log has incorrect info.  The identified input file and the original file name are two different files (see the attached example).  What is going on here Fernando?
[FSCAN.SCX.LOG](https://github.com/fdbozzo/foxbin2prg/files/1505685/FSCAN.SCX.LOG)

**Comment by fdbozzo** [comment] 2017-11-29 22:35
HI Rob!

Can you tell me, please, this info?:
- What version of FoxBin2Prg are you using
- The LOG attached is incomplete, header lines have important info missing 
- Are you using EXE syntax, PRG syntax or object syntax or how are you running the program
- Are you using the program alone or integrated with some Source Control tool or editor (name/version)?
- Can you attach the SCX/SCT file?

Thanks!

**Comment by RtBower** [comment] 2017-11-30 02:17
I am using the latest code from this repository with the vbscript named "Convert_VFP9_BIN_2_PRG.vbs".  This has nothing to do with the source control.  I simply ran your script from the "SendTo" folder on a top level folder of my project, which has many forms within, as instructed.  The form is attached.

[forms.zip](https://github.com/fdbozzo/foxbin2prg/files/1516305/forms.zip)

**Comment by fdbozzo** [comment] 2017-11-30 19:03
Ok, I think that I can --more or less-- replicate part of your LOG. Yes, it's not ok that bad LOG info appear, but you have nothing to care, generation is OK.
But anyway, I'm going to look at this to try to fix this.

Thanks Rob!

**Comment by RtBower** [comment] 2017-11-30 19:25
No, thank you Fernando for all this free work.  I just wanted to ensure this wasn't the sign of a bigger problem in the converted files.

**Comment by fdbozzo** [comment] 2017-12-01 19:11
Hi Rob,

There is a confirmed bug with latest version v1.19.48 and 49 of FoxBin2Prg. 
Please, use v1.19.47 until I fix it, and always have a backup if you don't use a Versioning Control System

You can check at [issue#9](https://github.com/fdbozzo/foxbin2prg/issues/9) to be notified when fixed.

Regards.-

**Comment by fdbozzo** [comment] 2017-12-03 13:37
Hi Rob:

Last bug (issue#9) I'd comment to you is now fixed. Please update to latest FoxBin2Prg from GitHub, and do not forget to copy all the files and not just FoxBin2Prg.exe/prg, because based on your attached LOG I can see that you don't have all the programs in place.

Once you have downloaded the latest version, and erased old FXPs (very important!), please, repeat the operation that did not make the correct LOG, to check if still happens

Thanks!

**Comment by RtBower** [comment] 2017-12-03 16:08
I've updated my local foxbin2prg repo, deleted all *.exe and *.fxp files, recompiled all projects, copied filename_caps.exe to the repo root folder, and rerun the Convert_VFP9_BIN_2_PRG.vbs script on my project folder.  The latest version of the example log file I provided initially is attached.
[FSCAN.SC2.LOG](https://github.com/fdbozzo/foxbin2prg/files/1524932/FSCAN.SC2.LOG)

**Comment by fdbozzo** [comment] 2017-12-03 18:27
It's really annoying why "freprint" keep showing in your log.

In order to be sure that there isn't a configuration or installation problem, I give you an example of a FoxBin2Prg typical installation, and tell me what differences with what you see with your installation:

- It's necessary to have a directory for FoxBin2Prg project only (in example: "**c:\vfp\foxbin2prg**", but you can use another) ==> Do not use the same directory of your application
- **In this directory**, it's necessary to have at minumum, this files: [foxbin2prg.exe, filename_caps.exe, fb2p_diff.exe, VFP9_FoxBin2Prg.vbs, Normalize_FileNames.vbs, Convert_VFP9_BIN_2_PRG.vbs, Convert_VFP9_PRG_2_BIN.vbs].
- Initially I suggest having ONLY this files in the FoxBin2Prg directory, and no sources (no PRG, no FXP, no subdirectories) so we make sure that there is no other interferences
- Scan your disk just in case you have another copy of foxbin2prg.* file in another directory, because this can interfere with the normal execution (mainly when an old copy is found in the PATH of execution)
- Make sure that in the "Send To" folder you have a clean shortcuts of Convert_VFP9_BIN_2_PRG.vbs, Convert_VFP9_PRG_2_BIN.vbs and FoxBin2Prg.exe (**Warning:** just the shortcuts, not a copy of the original programs! Please check this point)
- I suggest using the foxbin2prg.exe shortcut only (with the "INTERACTIVE-SHOWMSG" added in the shortcut, as explained in the README.md example table), because it can handle all convertion cases: TX2 single file, VFP binary fine and directory selection

Does occurs the same problem if you use the FoxBin2Prg.exe shortcut directly instead of the VBS scripts?

Thanks Rob!

**Closed** 2018-02-25 16:40 UTC

**Comment by fdbozzo** [comment] 2018-02-25 16:42
Closed because can't reproduce and there is a lack of data to continue looking at this.
