### ISSUE TITLE
Auto incrementing fields when importing data cause error

### ISSUE THREAD

**Issue by ngbrown** [fdbozzo/foxbin2prg#2] opened 2016-06-30 01:22 UTC
I'm trying the new configuration option `DBF_Conversion_Support: 8` and I get the following error on importing `db2` files for most of my tables:

```
Error 2088, Field ICONPK is read-only
```

The field name varies, but it appears that I get the error on the auto incrementing fields and there is data to import: 

```
<Autoinc_Nextval>1</Autoinc_Nextval>
<Autoinc_Step>1</Autoinc_Step>
```

It would probably be best to create the table without auto incrementing, then turn it back on after any data is inserted.  Using the greater of the highest inserted value for that column or the saved Autoinc_Nextval (because of the configuration parameter: `ExcludeDBFAutoincNextval`).

```
ALTER TABLE connects ALTER iconpk I AUTOINC NEXTVALUE 45
```

**Comment by ngbrown** [comment] 2016-06-30 02:04
Another thing, it picks up on the DBF configuration file, but doesn't seem to respect the `DBF_Conversion_Support` override in it:

```
****************************************************************************************************
MAIN EXECUTION  2016-06-29T18:53:09
****************************************************************************************************
> EXTERNAL PARAMETERS:
	tc_InputFile:                 C:\vfp_source\vfpapps\metadata\connects.db2
	tcType:                       PRG2BIN
	tcTextName:                   0
	tlGenText:                    0
	tcDontShowErrors:             1
	tcDebug:                      1
	tcDontShowProgress:           1
	tlRelanzarError:              (empty)
	tcOriginalFileName:           (empty)  -> Will use Default []
	tcRecompile:                  C:\vfp_source\vfpapps\metadata
	tcNoTimestamps:               1
	tcBackupLevels:               (empty)  -> Will use Default [0]
	tcClearUniqueID:              (empty)  -> Will use Default [.T.]
	tcOptimizeByFilestamp:        (empty)  -> Will use Default [0]

> USING THIS SETTINGS: C:\VFP_SOURCE\vfpapps\metadata\FOXBIN2PRG.CFG  => C:\vfp_source\vfpapps\metadata\connects.db2
> Option: PRG2BIN
> InputFile is a FILE

****************************************************************************************************
CONVERSION PROCESS  2016-06-29T18:53:09
****************************************************************************************************
> USING THIS SETTINGS: C:\VFP_SOURCE\vfpapps\metadata\FOXBIN2PRG.CFG  => C:\vfp_source\vfpapps\metadata\connects.db2
	c_OriginalFileName:           C:\vfp_source\vfpapps\metadata\connects.db2

	* Names capitalization program [C:\VFP_SOURCE\FOXBIN2PRG\filename_caps.exe] found
	c_foxbin2prg.changefileattribute >> [C:\vfp_source\vfpapps\metadata\connects.DBF] lnRet = 1, dwFileAttributes_Orig = 32
	c_foxbin2prg.changefileattribute >> [C:\vfp_source\vfpapps\metadata\connects.FPT] lnRet = 0, dwFileAttributes_Orig = -1
	c_foxbin2prg.changefileattribute >> [C:\vfp_source\vfpapps\metadata\connects.CDX] lnRet = 1, dwFileAttributes_Orig = 32

	> Found DBF configuration file: C:\vfp_source\vfpapps\metadata\connects.DBF.CFG
		connects.DBF.CFG > DBF_Conversion_Support: 4

Error 2088, Field ICONPK is read-only
analyzecodeblock, 24043
REPLACE (lcFieldName) WITH (luValue)
FoxBin2Prg: [C:\VFP_SOURCE\FOXBIN2PRG\FOXBIN2PRG.EXE] (EXE Version: v1.19.47)
tc_InputFile = [C:\VFP_SOURCE\vfpapps\metadata\CONNECTS.DB2]

Source file: C:\vfp_source\vfpapps\metadata\connects.db2
```

I would think with `connects.DBF.CFG > DBF_Conversion_Support: 4` it wouldn't try to create the DBF files, but as you see with the error, it is trying to create them.

**Comment by fdbozzo** [comment] 2016-07-05 21:45
Hi Nathan!

Very thanks for reporting it!
I've fixed the second bug about DBF_Conversion_Support not being respected. You can download the fix on VFPx (v1.19.48 Preview-2)
[https://vfpx.codeplex.com/releases/view/116407](https://vfpx.codeplex.com/releases/view/116407)

About the first report on autoinc fields, I can't reproduce it. I've created a DBC and a related DBF with 3 autoinc fields with different settings and it gets regenerated without problems.
For doing this I 1st create the field as Integer and once it's record values are replaced y modify the structure to convert it in autoinc (the same as you propose)

I'm not using DBC triggers, don't know if this can interfere here.

Can you confirm if with the new version you keep getting both problems?

Thanks! :D

**Comment by ngbrown** [comment] 2016-07-09 14:25
@fdbozzo On the autoinc database fields, were you able to import the previously exported data back into the recreated tables?  The data did have gaps in the autoinc fields (e.g. 1,2,4,8), because of previously deleted records.  There were no triggers, it was just a single table with no relations.

**Comment by fdbozzo** [comment] 2016-07-09 19:24
Hi Nathan:

Yes, I can reimport the data with the exactly same IDs that where exported.
I've atteched here a DB2 file (rename it, removing the ".txt" extension), on which you can see that the records have IDs of 30, 35, 40 and 45, and the ID_AUTOINC fields is defined with step 5 and NextVal 50 (which is 45 of the max ID + 5)

[fb2p_free.db2.txt](https://github.com/fdbozzo/foxbin2prg/files/355716/fb2p_free.db2.txt)

Using the Preview-2 available on VFPx, please convert it to DBF and check that preserves the IDs, than convert again to DB2 and check that all the IDs are exactly the same.

This is because I 1st import the data with this autoinc field as Integer (to preserve previous IDs) and finally I change the structure of the field to be autoinc and setting the nextval and the step.

If you keep having trouble, can you send me your DB2 and/or DBF file, so I can analyze it?

**Comment by ngbrown** [comment] 2016-07-09 22:13
I used v1.19.48 and still had the same problems.  I am using the Send To VFP9 PROG2BIN on the directory.

[foxbin2prg_data_conversion_test.zip](https://github.com/fdbozzo/foxbin2prg/files/355772/foxbin2prg_data_conversion_test.zip)

There are two folders; `originaldata` has the original FoxPro database container and table and the `foxbin2prg.cfg` settings to just output the text and data. The second folder, `datafromtext` copies those `.DB2` and `.DC2` files but has a `foxbin2prg.cfg` with `DBF_Conversion_Support` set to 8.  The conversion PROG2BIN fails.  If you can get it to work on your machine, then that will be very interesting.

Interestingly, when I put your above example file in the `datafromtext` folder and run PROG2BIN, I get the same error:

```
2016-07-09T14:27:45  ----------------------------------------------------------------------------------------------------
Error 2088, Field ID_AUTOINC is read-only
analyzecodeblock, 24081
REPLACE (lcFieldName) WITH (luValue)
FoxBin2Prg: [C:\VFP_SOURCE\FOXBIN2PRG\FOXBIN2PRG.EXE] (EXE Version: v1.19.48)
tc_InputFile = [C:\VFP_SOURCE\TEST\DATAFROMTEXT\FB2P_FREE.DB2]

Source file: C:\vfp_source\test\datafromtext\fb2p_free.db2
```

**Comment by fdbozzo** [comment] 2016-07-09 22:35
Nathan! I've found it! :D

Thanks for your example, now I can reproduce the problem!

It's caused by the "**ExcludeDBFAutoincNextval: 1**" option in the foxbin2prg.cfg file, that's why it didn't occur to me, because I haven't it excluded, so in my configuration it's respected by default.
If you comment temporalily this setting, then you should see that all works ok.

I'm going to review the functionallity of this option related to the export/import of data, and back to you when done.

Thanks! :D

**Comment by fdbozzo** [comment] 2016-07-09 23:13
Ok, fixed in **Preview-3**:
https://vfpx.codeplex.com/releases/view/116407

Please, confirm if it's fixed for you too.

Thanks!

**Comment by ngbrown** [comment] 2016-07-10 00:39
@fdbozzo.  Ok, it's now no longer generating an error, but I noticed that memo fields are not making the round trip.

For example, I have a memo field called `ckeyfield` and this is what BIN2PRG writes out to the `.DB2` file in a `<RECORD>`:

```
<CKEYFIELD><![CDATA[usr_pk]]></CKEYFIELD>
```

Well, the CDATA stuff ends up back into the FoxPro table when ran through PRG2BIN, and then when it's exported again through BIN2PRG there are two CDATA blocks in the XML contents for that field.

![screenshot - 2016-07-09 5_36_11 pm](https://cloud.githubusercontent.com/assets/228987/16711028/fb9551b2-45fb-11e6-9eb7-5f9b843ba4de.png)

**Comment by fdbozzo** [comment] 2016-07-10 07:48
Hi Nathan:

I'm sorry, when fixed the multi-line memo bug I've found while testing, introduced a new defect on which this CDATA is not removed.
This is because I've added some code to make the old DB2 files with data that used a memo data encoding in one line only compatible with the new format of the memo for supporting true multi-line because now using CDATA, so some memos can be compared now line-by-line.

I've uploaded the v1.19.48-Preview4 to VFPx with this fix:
https://vfpx.codeplex.com/releases/view/116407

**Comment by ngbrown** [comment] 2016-07-10 22:33
Preview 4 is working for this.

**Closed** 2016-07-10 22:41 UTC
Labels: bug
